<?php
return array (
  0 => 
  array (
    0 => 
    array (
      't_id' => '1',
      't_name' => '电影',
      't_enname' => 'dianying',
      't_sort' => '1',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '1,5,6,7,8,9,10,11',
    ),
    1 => 
    array (
      't_id' => '2',
      't_name' => '连续剧',
      't_enname' => 'lianxuju',
      't_sort' => '2',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '2,12,13,14,15',
    ),
    2 => 
    array (
      't_id' => '3',
      't_name' => '综艺',
      't_enname' => 'zongyi',
      't_sort' => '3',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_4,118_24,121_15,121_8,204_2,',
      'childids' => '3',
    ),
    3 => 
    array (
      't_id' => '4',
      't_name' => '动漫',
      't_enname' => 'dongman',
      't_sort' => '4',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_23,119_1,118_3,',
      'childids' => '4',
    ),
    4 => 
    array (
      't_id' => '5',
      't_name' => '动作片',
      't_enname' => 'dongzuopian',
      't_sort' => '11',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_8,116_8,201_5,',
      'childids' => '5',
    ),
    5 => 
    array (
      't_id' => '6',
      't_name' => '喜剧片',
      't_enname' => 'xijupian',
      't_sort' => '12',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_9,',
      'childids' => '6',
    ),
    6 => 
    array (
      't_id' => '7',
      't_name' => '爱情片',
      't_enname' => 'aiqingpian',
      't_sort' => '13',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_10,120_19,',
      'childids' => '7',
    ),
    7 => 
    array (
      't_id' => '8',
      't_name' => '科幻片',
      't_enname' => 'kehuanpian',
      't_sort' => '14',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_11,',
      'childids' => '8',
    ),
    8 => 
    array (
      't_id' => '9',
      't_name' => '恐怖片',
      't_enname' => 'kongbupian',
      't_sort' => '14',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_12,106_8,',
      'childids' => '9',
    ),
    9 => 
    array (
      't_id' => '10',
      't_name' => '剧情片',
      't_enname' => 'juqingpian',
      't_sort' => '16',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_7,',
      'childids' => '10',
    ),
    10 => 
    array (
      't_id' => '11',
      't_name' => '战争片',
      't_enname' => 'zhanzhengpian',
      't_sort' => '17',
      't_pid' => '1',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_13,106_7,',
      'childids' => '11',
    ),
    11 => 
    array (
      't_id' => '12',
      't_name' => '国产剧',
      't_enname' => 'guochanju',
      't_sort' => '21',
      't_pid' => '2',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_15,',
      'childids' => '12',
    ),
    12 => 
    array (
      't_id' => '13',
      't_name' => '港台剧',
      't_enname' => 'gangtaiju',
      't_sort' => '22',
      't_pid' => '2',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_16,',
      'childids' => '13',
    ),
    13 => 
    array (
      't_id' => '14',
      't_name' => '日韩剧',
      't_enname' => 'rihanju',
      't_sort' => '23',
      't_pid' => '2',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_18,119_13,203_7,',
      'childids' => '14',
    ),
    14 => 
    array (
      't_id' => '15',
      't_name' => '欧美剧',
      't_enname' => 'oumeiju',
      't_sort' => '24',
      't_pid' => '2',
      't_key' => '',
      't_des' => '',
      't_template' => 'vodlist.html',
      't_vodtemplate' => 'vod.html',
      't_playtemplate' => 'vodplay.html',
      't_hide' => '0',
      't_union' => ',118_17,118_19,201_19,202_11,',
      'childids' => '15',
    ),
  ),
  1 => 
  array (
    0 => 
    array (
      't_id' => '1',
      't_name' => '站内新闻',
      't_enname' => 'zhanneixinwen',
      't_sort' => '1',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '1',
    ),
    1 => 
    array (
      't_id' => '2',
      't_name' => '娱乐动态',
      't_enname' => 'yuledongtai',
      't_sort' => '2',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '2',
    ),
    2 => 
    array (
      't_id' => '3',
      't_name' => '八卦爆料',
      't_enname' => 'baguabaoliao',
      't_sort' => '3',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '3',
    ),
    3 => 
    array (
      't_id' => '4',
      't_name' => '影片资讯',
      't_enname' => 'yingpianzixun',
      't_sort' => '4',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '4',
    ),
    4 => 
    array (
      't_id' => '5',
      't_name' => '明星资讯',
      't_enname' => 'mingxingzixun',
      't_sort' => '5',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '5',
    ),
    5 => 
    array (
      't_id' => '6',
      't_name' => '电视资讯',
      't_enname' => 'dianshizixun',
      't_sort' => '6',
      't_pid' => '0',
      't_key' => '',
      't_des' => '',
      't_template' => 'artlist.html',
      't_arttemplate' => 'art.html',
      't_hide' => '0',
      't_union' => '',
      'childids' => '6',
    ),
  ),
  2 => 
  array (
    0 => 
    array (
      't_id' => '1',
      't_name' => 'aaaa',
      't_enname' => 'aaaa',
      't_sort' => '1',
      't_template' => 'topic.html',
      't_pic' => '',
      't_des' => 'aaaa',
    ),
    1 => 
    array (
      't_id' => '2',
      't_name' => 'bbb',
      't_enname' => 'bb',
      't_sort' => '2',
      't_template' => 'topic.html',
      't_pic' => 'bbb',
      't_des' => 'bbb',
    ),
    2 => 
    array (
      't_id' => '3',
      't_name' => 'ccc',
      't_enname' => 'ccc',
      't_sort' => '3',
      't_template' => 'topic.html',
      't_pic' => 'ccc',
      't_des' => 'ccc',
    ),
    3 => 
    array (
      't_id' => '4',
      't_name' => 'dddd',
      't_enname' => 'dd',
      't_sort' => '4',
      't_template' => 'topic.html',
      't_pic' => 'ddd',
      't_des' => 'dddd',
    ),
    4 => 
    array (
      't_id' => '5',
      't_name' => 'eee',
      't_enname' => 'eee',
      't_sort' => '5',
      't_template' => 'topic.html',
      't_pic' => 'eee',
      't_des' => 'eee',
    ),
    5 => 
    array (
      't_id' => '6',
      't_name' => 'fff',
      't_enname' => 'ffff',
      't_sort' => '6',
      't_template' => 'topic.html',
      't_pic' => 'fff',
      't_des' => 'ffff',
    ),
  ),
  3 => 
  array (
  ),
  4 => 
  array (
    0 => '﻿大陆',
    1 => '港台',
    2 => '日韩',
    3 => '欧美',
    4 => '亚洲',
    5 => '非洲',
    6 => '其他',
  ),
  5 => 
  array (
    0 => '﻿汉语',
    1 => '粤语',
    2 => '英语',
    3 => '日语',
    4 => '韩语',
  ),
  6 => 
  array (
    0 => 
    array (
      'ug_id' => '1',
      'ug_name' => '普通会员',
      'ug_type' => '',
      'ug_popedom' => '',
      'ug_upgrade' => '0',
      'ug_popvalue' => '1',
    ),
  ),
);
?>